version: '2'
services:
  yopa:
    container_name: goaws
    image: pafortin/goaws:1.0.1
    ports:
      - 4100:4100
    volumes:
     - ./etc/local:/conf
    entrypoint: "/goaws_linux_amd64 -debug"
